CLASSE:
  connection: doctrine
  tableName: CLASSE
  columns:
    id_classe:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    id_niveau:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    nom:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    NIVEAU:
      local: id_niveau
      foreign: id_niveau
      type: one
    POST_CLASSE:
      local: id_classe
      foreign: id_classe
      type: many
    UTILISATEUR_CLASSE:
      local: id_classe
      foreign: id_classe
      type: many
ETABLISSEMENT:
  connection: doctrine
  tableName: ETABLISSEMENT
  columns:
    id_etablissement:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    nom:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    adresse:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    code_postal:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    ville:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    telephone_1:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    telephone_2:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    fax:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    NIVEAU:
      local: id_etablissement
      foreign: id_etablissement
      type: many
    POST_ETABLISSEMENT:
      local: id_etablissement
      foreign: id_etablissement
      type: many
    UTILSATEUR_ETABLISSEMENT:
      local: id_etablissement
      foreign: id_etablissement
      type: many
NIVEAU:
  connection: doctrine
  tableName: NIVEAU
  columns:
    id_niveau:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    id_etablissement:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    nom:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    ETABLISSEMENT:
      local: id_etablissement
      foreign: id_etablissement
      type: one
    CLASSE:
      local: id_niveau
      foreign: id_niveau
      type: many
    POST_NIVEAU:
      local: id_niveau
      foreign: id_niveau
      type: many
    UTILISATEUR_NIVEAU:
      local: id_niveau
      foreign: id_niveau
      type: many
POST:
  connection: doctrine
  tableName: POST
  columns:
    id_post:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    id_user:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    titre:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    date_creation:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    date_derniere_modification:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    contenu:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    UTILISATEUR:
      local: id_user
      foreign: id_user
      type: one
    POST_CLASSE:
      local: id_post
      foreign: id_post
      type: many
    POST_ETABLISSEMENT:
      local: id_post
      foreign: id_post
      type: many
    POST_NIVEAU:
      local: id_post
      foreign: id_post
      type: many
POST_CLASSE:
  connection: doctrine
  tableName: POST_CLASSE
  columns:
    id_post:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    id_classe:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
  relations:
    CLASSE:
      local: id_classe
      foreign: id_classe
      type: one
    POST:
      local: id_post
      foreign: id_post
      type: one
POST_ETABLISSEMENT:
  connection: doctrine
  tableName: POST_ETABLISSEMENT
  columns:
    id_post:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    id_etablissement:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
  relations:
    ETABLISSEMENT:
      local: id_etablissement
      foreign: id_etablissement
      type: one
    POST:
      local: id_post
      foreign: id_post
      type: one
POST_NIVEAU:
  connection: doctrine
  tableName: POST_NIVEAU
  columns:
    id_post:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    id_niveau:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
  relations:
    NIVEAU:
      local: id_niveau
      foreign: id_niveau
      type: one
    POST:
      local: id_post
      foreign: id_post
      type: one
TYPE_UTILISATEUR:
  connection: doctrine
  tableName: TYPE_UTILISATEUR
  columns:
    id_type_utilisateur:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    valeur:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    libelle:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    UTILISATEUR_TYPE_UTILISATEUR:
      local: id_type_utilisateur
      foreign: id_type_utilisateur
      type: many
UTILISATEUR:
  connection: doctrine
  tableName: UTILISATEUR
  columns:
    id_user:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    nom:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    prenom:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    login:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    mot_de_passe:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
    POST:
      local: id_user
      foreign: id_user
      type: many
    UTILISATEUR_CLASSE:
      local: id_user
      foreign: id_user
      type: many
    UTILISATEUR_NIVEAU:
      local: id_user
      foreign: id_user
      type: many
    UTILISATEUR_TYPE_UTILISATEUR:
      local: id_user
      foreign: id_user
      type: many
    UTILSATEUR_ETABLISSEMENT:
      local: id_user
      foreign: id_user
      type: many
UTILISATEUR_CLASSE:
  connection: doctrine
  tableName: UTILISATEUR_CLASSE
  columns:
    id_classe:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    id_user:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
  relations:
    UTILISATEUR:
      local: id_user
      foreign: id_user
      type: one
    CLASSE:
      local: id_classe
      foreign: id_classe
      type: one
UTILISATEUR_NIVEAU:
  connection: doctrine
  tableName: UTILISATEUR_NIVEAU
  columns:
    id_niveau:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    id_user:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
  relations:
    UTILISATEUR:
      local: id_user
      foreign: id_user
      type: one
    NIVEAU:
      local: id_niveau
      foreign: id_niveau
      type: one
UTILISATEUR_TYPE_UTILISATEUR:
  connection: doctrine
  tableName: UTILISATEUR_TYPE_UTILISATEUR
  columns:
    id_user:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    id_type_utilisateur:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
  relations:
    TYPE_UTILISATEUR:
      local: id_type_utilisateur
      foreign: id_type_utilisateur
      type: one
    UTILISATEUR:
      local: id_user
      foreign: id_user
      type: one
UTILSATEUR_ETABLISSEMENT:
  connection: doctrine
  tableName: UTILSATEUR_ETABLISSEMENT
  columns:
    id_etablissement:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    id_user:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
  relations:
    UTILISATEUR:
      local: id_user
      foreign: id_user
      type: one
    ETABLISSEMENT:
      local: id_etablissement
      foreign: id_etablissement
      type: one
