<?php
include_once("constant/constants.php");
include_once("dao/baseDao.php");
include_once("dao/utilisateurDao.php");
include_once("bean/utilisateur.php");
include_once("dao/etablissementDao.php");
include_once("bean/etablissement.php");
include_once("bean/type_utilisateur.php");
include_once("dao/utilisateurEtablissementDao.php");