INSERT INTO `ETABLISSEMENT` (`ID_ETABLISSEMENT`, `NOM`, `ADRESSE`, `CODE_POSTAL`, `VILLE`, `TELEPHONE_1`, `TELEPHONE_2`, `FAX`) VALUES
(2, 'Lycée Saint Martin', '29 rue d''antrain', '35000', 'Rennes', '02.99.01.02.03', '02.99.01.02.04', '02.99.01.02.05');

--
-- Contenu de la table `UTILISATEUR`
--

INSERT INTO `UTILISATEUR` (`ID_USER`, `NOM`, `PRENOM`, `LOGIN`, `MOT_DE_PASSE`) VALUES
(5, 'SOURDRILLE', 'Guillaume', 'edenyorke', 'fc2789a2f2f3303f7322efa51bb5882fe034a321');

--
-- Contenu de la table `UTILISATEUR_ETABLISSEMENT`
--

INSERT INTO `UTILISATEUR_ETABLISSEMENT` (`ID_ETABLISSEMENT`, `ID_USER`) VALUES
(2, 5);

--
-- Contenu de la table `UTILISATEUR_TYPE_UTILISATEUR`
--

INSERT INTO `UTILISATEUR_TYPE_UTILISATEUR` (`ID_USER`, `ID_TYPE_UTILISATEUR`) VALUES
