<?php

/**
 * NIVEAUTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NIVEAUTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NIVEAUTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NIVEAU');
    }
}