<?php

/**
 * POSTTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class POSTTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object POSTTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('POST');
    }
}