<?php

/**
 * POST_ETABLISSEMENTTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class POST_ETABLISSEMENTTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object POST_ETABLISSEMENTTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('POST_ETABLISSEMENT');
    }
}