<?php

/**
 * UTILSATEUR_ETABLISSEMENTTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UTILSATEUR_ETABLISSEMENTTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UTILSATEUR_ETABLISSEMENTTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UTILSATEUR_ETABLISSEMENT');
    }
}