<?php

/**
 * UTILISATEUR_NIVEAUTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UTILISATEUR_NIVEAUTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UTILISATEUR_NIVEAUTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UTILISATEUR_NIVEAU');
    }
}