<?php

/**
 * UTILISATEUR_NIVEAU
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UTILISATEUR_NIVEAU extends BaseUTILISATEUR_NIVEAU
{

}