<?php

/**
 * UTILISATEURTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UTILISATEURTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UTILISATEURTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UTILISATEUR');
    }
}