<?php
include_once("constant/constants.php");
include_once("dao/baseDao.php");
include_once("dao/utilisateurDao.php");
include_once("bean/utilisateur.php");
include_once("dao/etablissementDao.php");
include_once("bean/etablissement.php");
include_once("bean/type_utilisateur.php");
include_once("bean/niveau.php");
include_once("dao/niveauDao.php");
include_once("bean/classe.php");
include_once("dao/classeDao.php");
include_once ("logs/Logger.class.php");
include_once ("utils/file_utils.php");
include_once("bean/post.php");
include_once("dao/postDao.php");
include_once("bean/commentaire.php");
include_once("dao/commentaireDao.php");
include_once("bean/piece_jointe.php");
include_once("dao/pieceJointeDao.php");
include_once("utils/string_utils.php");
include_once("bean/association.php");
include_once("enums/typePost.php");
include_once("utils/post_utils.php");
include_once("utils/encrypt_utils.php");
