<?php

/**
 * POST_NIVEAUTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class POST_NIVEAUTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object POST_NIVEAUTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('POST_NIVEAU');
    }
}