<?php

/**
 * POST_CLASSETable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class POST_CLASSETable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object POST_CLASSETable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('POST_CLASSE');
    }
}