<?php

/**
 * TYPE_UTILISATEURTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TYPE_UTILISATEURTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TYPE_UTILISATEURTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TYPE_UTILISATEUR');
    }
}