<?php

/**
 * UTILISATEUR_TYPE_UTILISATEURTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UTILISATEUR_TYPE_UTILISATEURTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UTILISATEUR_TYPE_UTILISATEURTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UTILISATEUR_TYPE_UTILISATEUR');
    }
}