<?php

/**
 * UTILISATEUR_CLASSETable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UTILISATEUR_CLASSETable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UTILISATEUR_CLASSETable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UTILISATEUR_CLASSE');
    }
}